# Generated by Django 4.2.1 on 2023-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='titulo',
        ),
        migrations.DeleteModel(
            name='Practica',
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='ejercicios',
            field=models.ManyToManyField(to='Ejercicios.ejercicio'),
        ),
    ]
