# Generated by Django 4.2.1 on 2023-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuario_groups_usuario_is_staff_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, default='img_porfile/default.png', null=True, upload_to='media/'),
        ),
    ]
