# Generated by Django 4.2.1 on 2023-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0006_alter_grupo_imagen'),
        ('Usuarios', '0004_usuario_imagen_de_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='grupo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupos_inscritos',
            field=models.ManyToManyField(blank=True, related_name='alumnos_inscritos', to='Grupos.grupo'),
        ),
    ]
