# Generated by Django 4.2.1 on 2023-06-27 04:03

import Grupos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0005_alter_grupo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='imagen',
            field=models.ImageField(blank=True, default=Grupos.models.default_imagen, null=True, upload_to='media/'),
        ),
    ]
